---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: japower-release
  namespace: japower-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: japower-release-role
  namespace: japower-tenant
rules:
  - apiGroups: ["appstudio.redhat.com"]
    resources: ["releases", "releaseplans", "snapshots"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: japower-release-rolebinding
  namespace: japower-tenant
subjects:
  - kind: ServiceAccount
    name: japower-release
    namespace: japower-tenant
roleRef:
  kind: Role
  name: japower-release-role
  apiGroup: rbac.authorization.k8s.io
---
