apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: promote-to-candidate
spec:
  description: |
    A Release pipeline designed to gather release candidate images.
  params:
    - name: snapshot
      type: string
      description: The namespaced name (namespace/name) of the Snapshot
  tasks:
    - name: parse-snapshot
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/JasonPowr/konflux-release-test.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/parse-snapshot.yaml
      params:
        - name: snapshot
          value: $(params.snapshot)
      workspaces:
        - name: output
          workspace: release-workspace
    - name: verify-its
      runAfter:
        - parse-snapshot
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/JasonPowr/konflux-release-test.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/verify-its.yaml
      params:
        - name: snapshotStatus
          value: "$(tasks.parse-snapshot.results.snapshotStatus)"
      workspaces:
        - name: output
          workspace: release-workspace
  workspaces:
    - name: release-workspace
