apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: parse-snapshot
spec:
  description: >-
    Tekton task to collect release metadata
  workspaces:
    - name: output
  params:
    - name: snapshot
      type: string
      description: The namespaced name of the Snapshot
  results:
    - name: snapshotSpec
      description: A JSON object containing Snapshot info
    - name: snapshotStatus
      description: A JSON object containing Snapshot info
  steps:
    - name: collect-snapshot-spec
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      workingDir: /workspace/output/source
      env:
        - name: SNAPSHOT
          value: '$(params.snapshot)'
      script: |
        #!/usr/bin/env sh
        set -eo pipefail

        echo -e "\nFetching Snapshot Details..."
        SNAPSHOT_SPEC=$(get-resource "snapshot" "${SNAPSHOT}" "{.spec}")
        SNAPSHOT_NAME=$(get-resource "snapshot" "${SNAPSHOT}" "{.metadata.name}")
        SNAPSHOT_CREATION_TIMESTAMP=$(get-resource "snapshot" "${SNAPSHOT}" "{.metadata.creationTimestamp}")
        SNAPSHOT_SHA_URL=$(get-resource "snapshot" "${SNAPSHOT}" '{.metadata.annotations["pac.test.appstudio.openshift.io/sha-url"]}')

        SNAPSHOT_SPEC_JSON=$(
          jq -n \
            --arg name "$SNAPSHOT_NAME" \
            --arg creation "$SNAPSHOT_CREATION_TIMESTAMP" \
            --arg sha_url "$SNAPSHOT_SHA_URL" \
            --argjson spec "$SNAPSHOT_SPEC" \
            '{
              "snapshot_name": $name,
              "snapshot_creation_timestamp": $creation,
              "snapshot_spec": $spec,
              "snapshot_sha_url": $sha_url
            }'
        )

        echo -e "\nFetched Snapshot:"
        echo -e "$SNAPSHOT_SPEC_JSON"
        echo -n "$SNAPSHOT_SPEC_JSON" > "$(results.snapshotSpec.path)"

        echo -e "\nFetching Snapshot Status..."
        SNAPSHOT_STATUS=$(get-resource "snapshot" "${SNAPSHOT}" "{.status}")

        SNAPSHOT_STATUS_JSON=$(
          jq -n --argjson status "$SNAPSHOT_STATUS" \
            '{
              "snapshot_status": $status
            }'
        )

        echo -e "$SNAPSHOT_STATUS_JSON"
        echo -n "$SNAPSHOT_STATUS_JSON" > "$(results.snapshotStatus.path)"

