apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: parse-metadata
spec:
  description: >-
    Tekton task to collect release metadata
  params:
    - name: snapshot
      type: string
      description: The namespaced name of the Snapshot
  results:
    - name: snapshotSpec
      type: string
  steps:
    - name: collect-snapshot-spec
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      env:
        - name: SNAPSHOT
          value: '$(params.snapshot)'
      script: |
        #!/usr/bin/env sh
        set -eo pipefail

        echo -e "\nFetching Snapshot Spec"
        SNAPSHOT_SPEC=$(get-resource "snapshot" "${SNAPSHOT}" "{.spec}")

        echo "Snapshot Spec:"
        echo "${SNAPSHOT_SPEC}"

        echo "${SNAPSHOT_SPEC}" > "$(results.snapshotSpec.path)"
